### ISSUE TITLE
Postgres Kafka Debezium Issue with Schema Registery 

### ISSUE THREAD

**Issue by soumilshah1995** [ninadingole/docker-images#4]
Hey 
I have tried your example and I was able to register the connector and issue is I am not able to see schema in schema prehistory 
<img width="1599" alt="Screenshot 2023-11-25 at 1 31 29 PM" src="https://github.com/ninadingole/docker-compose-stacks/assets/39345855/b0f586ae-8d29-4da0-bb7f-518794aa3947">

curl -X GET http://localhost:8081/subjects/postgres.public.movies/versions/1

```
{"error_code":40401,"message":"Subject 'postgres.public.movies' not found."}% 
```

**Comment by ninadingole** [comment]
ok will take a look thanks for reporting

**Comment by soumilshah1995** [comment]
Thanks

**Comment by ninadingole** [comment]
Ok so the schema is missing and is not getting registered. I will add the schema file soon :)

**Comment by soumilshah1995** [comment]
Thanks actually I used different docker image for my POC 
in case if you are interested 
```
version: '3'

services:
  fast-data-dev:
    image: dougdonohoe/fast-data-dev
    ports:
      - "3181:3181"
      - "3040:3040"
      - "7081:7081"
      - "7082:7082"
      - "7083:7083"
      - "7092:7092"
      - "8081:8081"
    environment:
      - ZK_PORT=3181
      - WEB_PORT=3040
      - REGISTRY_PORT=8081
      - REST_PORT=7082
      - CONNECT_PORT=7083
      - BROKER_PORT=7092
      - ADV_HOST=127.0.0.1

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

```
